---
name: snyk-ls
description: |
  The language server follows the Language Server Protocol and integrates with Snyk Open Source, Snyk Infrastructure as Code and Snyk Code. 
  For the former two, it uses the Snyk CLI as a data provider, for the latter it is connecting directly to the Snyk Code API.
homepage: https://github.com/snyk/snyk-ls
licenses:
  - Apache-2.0
languages: []
categories:
  - LSP

source:
  id: pkg:github/snyk/snyk-ls@20230825.153120
  asset:
    - target: darwin_x64
      file: snyk-ls_{{version}}_darwin_amd64
      bin: snyk-ls
    - target: darwin_arm64
      file: snyk-ls_{{version}}_darwin_arm64
      bin: snyk-ls
    - target: linux_x64
      file: snyk-ls_{{version}}_linux_amd64
      bin: snyk-ls
    - target: linux_x86
      file: snyk-ls_{{version}}_linux_386
      bin: snyk-ls
    - target: linux_arm64
      file: snyk-ls_{{version}}_linux_arm64
      bin: snyk-ls
    - target: win_x86
      file: snyk-ls_{{version}}_windows_386.exe
      bin: snyk-ls.exe
    - target: win_x64
      file: snyk-ls_{{version}}_windows_amd64.exe
      bin: snyk-ls.exe

bin:
  snyk-ls: "{{source.asset.bin}}"
